[2024-06-26T04:32:24.824+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T04:32:24.838+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_movie_dataset_v28.insert_data_to_db scheduled__2024-06-25T12:00:00+00:00 [queued]>
[2024-06-26T04:32:24.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_movie_dataset_v28.insert_data_to_db scheduled__2024-06-25T12:00:00+00:00 [queued]>
[2024-06-26T04:32:24.844+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-26T04:32:24.852+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): insert_data_to_db> on 2024-06-25 12:00:00+00:00
[2024-06-26T04:32:24.857+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4696) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T04:32:24.858+0000] {standard_task_runner.py:63} INFO - Started process 4698 to run task
[2024-06-26T04:32:24.858+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'create_movie_dataset_v28', 'insert_data_to_db', 'scheduled__2024-06-25T12:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp09a3ic_s']
[2024-06-26T04:32:24.859+0000] {standard_task_runner.py:91} INFO - Job 156: Subtask insert_data_to_db
[2024-06-26T04:32:24.893+0000] {task_command.py:426} INFO - Running <TaskInstance: create_movie_dataset_v28.insert_data_to_db scheduled__2024-06-25T12:00:00+00:00 [running]> on host ad6ccfebc5a6
[2024-06-26T04:32:24.948+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='create_movie_dataset_v28' AIRFLOW_CTX_TASK_ID='insert_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T12:00:00+00:00'
[2024-06-26T04:32:24.948+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T04:32:24.955+0000] {sql.py:276} INFO - Executing: 
[2024-06-26T04:32:24.962+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-06-26T04:32:24.963+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T04:32:24.963+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 409, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2024-06-26T04:32:24.970+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=create_movie_dataset_v28, task_id=insert_data_to_db, run_id=scheduled__2024-06-25T12:00:00+00:00, execution_date=20240625T120000, start_date=20240626T043224, end_date=20240626T043224
[2024-06-26T04:32:24.978+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 156 for task insert_data_to_db (List of SQL statements is empty; 4698)
[2024-06-26T04:32:24.991+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T04:32:25.001+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T04:32:25.003+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
