[2024-06-25T22:14:51.800+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T22:14:51.816+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_movie_dataset_v2.get_movies scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-25T22:14:51.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_movie_dataset_v2.get_movies scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-25T22:14:51.822+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-25T22:14:51.834+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_movies> on 2024-06-25 00:00:00+00:00
[2024-06-25T22:14:51.839+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=833) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T22:14:51.839+0000] {standard_task_runner.py:63} INFO - Started process 834 to run task
[2024-06-25T22:14:51.840+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'create_movie_dataset_v2', 'get_movies', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpamfdng43']
[2024-06-25T22:14:51.840+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask get_movies
[2024-06-25T22:14:51.874+0000] {task_command.py:426} INFO - Running <TaskInstance: create_movie_dataset_v2.get_movies scheduled__2024-06-25T00:00:00+00:00 [running]> on host ad6ccfebc5a6
[2024-06-25T22:14:51.928+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='create_movie_dataset_v2' AIRFLOW_CTX_TASK_ID='get_movies' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-25T22:14:51.929+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T22:14:53.597+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T22:14:53.601+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/get_movies.py", line 16, in get_movies
    with open("data/movie_data.json", "w", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/movie_data.json'
[2024-06-25T22:14:53.617+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=create_movie_dataset_v2, task_id=get_movies, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240625T221451, end_date=20240625T221453
[2024-06-25T22:14:53.626+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task get_movies ([Errno 2] No such file or directory: 'data/movie_data.json'; 834)
[2024-06-25T22:14:53.656+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T22:14:53.667+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T22:14:53.670+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-25T22:18:03.384+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T22:18:03.398+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_movie_dataset_v2.get_movies scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-25T22:18:03.404+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_movie_dataset_v2.get_movies scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-25T22:18:03.404+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-25T22:18:03.413+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_movies> on 2024-06-25 00:00:00+00:00
[2024-06-25T22:18:03.416+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=949) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T22:18:03.417+0000] {standard_task_runner.py:63} INFO - Started process 950 to run task
[2024-06-25T22:18:03.417+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'create_movie_dataset_v2', 'get_movies', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp4aoq5f75']
[2024-06-25T22:18:03.418+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask get_movies
[2024-06-25T22:18:03.450+0000] {task_command.py:426} INFO - Running <TaskInstance: create_movie_dataset_v2.get_movies scheduled__2024-06-25T00:00:00+00:00 [running]> on host ad6ccfebc5a6
[2024-06-25T22:18:03.501+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='create_movie_dataset_v2' AIRFLOW_CTX_TASK_ID='get_movies' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-25T22:18:03.502+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T22:18:08.444+0000] {logging_mixin.py:188} INFO - Данные успешно сохранены в файл 'movie_data.json'.
[2024-06-25T22:18:08.445+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-25T22:18:08.446+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T22:18:08.452+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=create_movie_dataset_v2, task_id=get_movies, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240625T221803, end_date=20240625T221808
[2024-06-25T22:18:08.466+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T22:18:08.476+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T22:18:08.479+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
