[2024-07-08T05:31:51.883+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T05:31:51.894+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_v63.test_postgres_connection scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-08T05:31:51.899+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_v63.test_postgres_connection scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-08T05:31:51.899+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T05:31:51.909+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_postgres_connection> on 2024-07-07 00:00:00+00:00
[2024-07-08T05:31:51.915+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=247) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T05:31:51.915+0000] {standard_task_runner.py:63} INFO - Started process 295 to run task
[2024-07-08T05:31:51.915+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'model_training_v63', 'test_postgres_connection', 'scheduled__2024-07-07T00:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/model_training.py', '--cfg-path', '/tmp/tmp6hveh5nc']
[2024-07-08T05:31:51.917+0000] {standard_task_runner.py:91} INFO - Job 127: Subtask test_postgres_connection
[2024-07-08T05:31:51.949+0000] {task_command.py:426} INFO - Running <TaskInstance: model_training_v63.test_postgres_connection scheduled__2024-07-07T00:00:00+00:00 [running]> on host 2568aaedadee
[2024-07-08T05:31:52.001+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='model_training_v63' AIRFLOW_CTX_TASK_ID='test_postgres_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-07T00:00:00+00:00'
[2024-07-08T05:31:52.002+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T05:31:52.014+0000] {logging_mixin.py:188} INFO - You are connected to -  ('PostgreSQL 15.7 (Debian 15.7-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit',) 
[2024-07-08T05:31:52.014+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-08T05:31:52.015+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T05:31:52.021+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=model_training_v63, task_id=test_postgres_connection, run_id=scheduled__2024-07-07T00:00:00+00:00, execution_date=20240707T000000, start_date=20240708T053151, end_date=20240708T053152
[2024-07-08T05:31:52.048+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T05:31:52.059+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T05:31:52.062+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
