[2024-07-06T12:52:03.614+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-06T12:52:03.624+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_v43.get_data scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-07-06T12:52:03.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_v43.get_data scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-07-06T12:52:03.628+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-06T12:52:03.637+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-07-05 00:00:00+00:00
[2024-07-06T12:52:03.642+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-06T12:52:03.643+0000] {standard_task_runner.py:63} INFO - Started process 6979 to run task
[2024-07-06T12:52:03.643+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'model_training_v43', 'get_data', 'scheduled__2024-07-05T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/model_training.py', '--cfg-path', '/tmp/tmpt653r8kg']
[2024-07-06T12:52:03.644+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask get_data
[2024-07-06T12:52:03.675+0000] {task_command.py:426} INFO - Running <TaskInstance: model_training_v43.get_data scheduled__2024-07-05T00:00:00+00:00 [running]> on host fba33172adc1
[2024-07-06T12:52:03.733+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='model_training_v43' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-05T00:00:00+00:00'
[2024-07-06T12:52:03.735+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-06T12:52:03.749+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-07-06T12:52:03.800+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py:243: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2024-07-06T12:52:04.461+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-06T12:52:04.462+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-06T12:52:04.470+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=model_training_v43, task_id=get_data, run_id=scheduled__2024-07-05T00:00:00+00:00, execution_date=20240705T000000, start_date=20240706T125203, end_date=20240706T125204
[2024-07-06T12:52:04.498+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-06T12:52:04.511+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-06T12:52:04.514+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
