[2024-07-10T23:17:22.037+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T23:17:22.048+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_v77.get_data scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T23:17:22.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_v77.get_data scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T23:17:22.054+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-10T23:17:22.063+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-07-09 00:00:00+00:00
[2024-07-10T23:17:22.069+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6079) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T23:17:22.070+0000] {standard_task_runner.py:63} INFO - Started process 6100 to run task
[2024-07-10T23:17:22.069+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'model_training_v77', 'get_data', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/model_training.py', '--cfg-path', '/tmp/tmpfv7_3yd8']
[2024-07-10T23:17:22.071+0000] {standard_task_runner.py:91} INFO - Job 143: Subtask get_data
[2024-07-10T23:17:22.105+0000] {task_command.py:426} INFO - Running <TaskInstance: model_training_v77.get_data scheduled__2024-07-09T00:00:00+00:00 [running]> on host 95d2f1320dbe
[2024-07-10T23:17:22.160+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='model_training_v77' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T23:17:22.161+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T23:17:22.176+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-07-10T23:17:22.222+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py:243: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2024-07-10T23:17:22.350+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-10T23:17:22.350+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T23:17:22.358+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=model_training_v77, task_id=get_data, run_id=scheduled__2024-07-09T00:00:00+00:00, execution_date=20240709T000000, start_date=20240710T231722, end_date=20240710T231722
[2024-07-10T23:17:22.404+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-10T23:17:22.438+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-10T23:17:22.461+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
