[2024-07-13T02:32:27.345+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T02:32:27.356+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_v86.get_data scheduled__2024-07-12T00:00:00+00:00 [queued]>
[2024-07-13T02:32:27.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_v86.get_data scheduled__2024-07-12T00:00:00+00:00 [queued]>
[2024-07-13T02:32:27.362+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-13T02:32:27.371+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-07-12 00:00:00+00:00
[2024-07-13T02:32:27.377+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1114) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-13T02:32:27.378+0000] {standard_task_runner.py:63} INFO - Started process 1135 to run task
[2024-07-13T02:32:27.378+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'model_training_v86', 'get_data', 'scheduled__2024-07-12T00:00:00+00:00', '--job-id', '406', '--raw', '--subdir', 'DAGS_FOLDER/model_training.py', '--cfg-path', '/tmp/tmp55nbaopq']
[2024-07-13T02:32:27.379+0000] {standard_task_runner.py:91} INFO - Job 406: Subtask get_data
[2024-07-13T02:32:27.410+0000] {task_command.py:426} INFO - Running <TaskInstance: model_training_v86.get_data scheduled__2024-07-12T00:00:00+00:00 [running]> on host 0e0c69066946
[2024-07-13T02:32:27.462+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='model_training_v86' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-12T00:00:00+00:00'
[2024-07-13T02:32:27.465+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T02:32:27.530+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-07-13T02:32:27.571+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py:243: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2024-07-13T02:32:27.974+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-13T02:32:27.974+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T02:32:27.982+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=model_training_v86, task_id=get_data, run_id=scheduled__2024-07-12T00:00:00+00:00, execution_date=20240712T000000, start_date=20240713T023227, end_date=20240713T023227
[2024-07-13T02:32:28.032+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-13T02:32:28.051+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-13T02:32:28.053+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
